---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: web-app
  labels:
    app: website
spec:
  replicas: 2
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: amazonaws.com/web-app
        ports:
        - containerPort: 3000
          name: website
